# University Academic Performance Analysis Using NumPy

## 📄 Problem Statement
- Modern universities generate large volumes of academic data across multiple subjects and students. Efficient numerical analysis of this structured data is essential for understanding student performance trends, identifying academic strengths and weaknesses, and supporting data-driven decision-making.

- In this project, a dataset representing the marks of 500 students across 8 subjects is analyzed using NumPy 2D arrays. The goal is to perform structured academic performance evaluation through numerical computation and matrix-based operations.

## Objectives of the Study

The primary objective of this project is to analyze large-scale academic performance data using NumPy 2D arrays and numerical computing techniques.

The specific objectives of this study are:

- To structure student academic records into a two-dimensional matrix format.
- To examine overall and subject-wise performance trends across 500 students.
- To compute total marks and percentage scores for each student.
- To evaluate average performance in each subject across the university.
- To measure the variation and distribution of marks using statistical analysis.
- To identify high-performing students and academically at-risk students.
- To apply uniform grace marks using broadcasting techniques.
- To demonstrate array reshaping, transformation, and concatenation operations.
- To perform logical filtering for academic classification.
- To strengthen understanding of NumPy fundamentals including indexing, slicing, and matrix operations.

This project aims to build a strong numerical computing foundation required for advanced data science and machine learning applications.

### Importing numpy library

In [1]:
import numpy as np

## Step 1: Creation of Academic Performance Dataset

The first step involves generating a structured academic dataset 
representing marks of 500 students across 8 subjects.

Each row represents an individual student.
Each column represents a subject.

All marks are generated within the range of 0 to 100.

In [2]:
np.random.seed(42)

results = np.random.randint(0, 101, size=(500, 8))
results.shape

(500, 8)

## Step 2: Examination of Dataset Structure and Properties

The dataset is examined to understand its size, dimensionality, 
and storage characteristics before performing further analysis.

### Total number of students

In [4]:
print("Number of Students:", results.shape[0])

Number of Students: 500


### Total subjects

In [5]:
print("Number of Subjects:", results.shape[1])

Number of Subjects: 8


### Total number of records

In [6]:
print("Total Records:", results.size)

Total Records: 4000


### Number of Dimensions

In [7]:
print("Number of Dimensions:", results.ndim)

Number of Dimensions: 2


### DataType  of elements store in Array

In [8]:
print("Data Type:", results.dtype)

Data Type: int32


## Step 3: Accessing Individual and Subject-Wise Records

In this step, we retrieve:
- Marks obtained by the first student
- Marks scored in a particular subject by all students
- Records of the first ten students

### Marks obtained by the first student

In [9]:
print("Marks of First Student:", results[0])

Marks of First Student: [51 92 14 71 60 20 82 86]


### Marks scored in a particular subject by all students

In [10]:
print("Marks in Subject 3:", results[:, 2])

Marks in Subject 3: [ 14  87  29  57  59  54  38  52  46   5  43  14  81  14   7  32  33  43
  77  78  51  28  65  43  96  26  78  51  58  96  69  23  72  35  51  56
   6  68   2  35  17  99   7  85  26  68  16  36  96  24  46  32  98  35
  86  85  57  59   5  15  57  11   0  66  28  75  32  51   3  83  50  73
   1  73  35  63  22  88  12  75  15  52  38  17  12  28  70  60  66  60
  24  31 100  48  86  75  57  63  91  46  64  88  98  94  73  50  91  49
  16  74  81  37  28  87  74   3  92  81   4  44  62  98  27  55  63  85
  67  39  63  52  61  30  83  61  44  96  37  49  39   8  48  33  59  29
  61  38  14  50  71  35  32  37  14  44  26  22  81   4  77 100  62  52
  62  90  23  28  80  48  55  92  46   0  82   6  58   7  15  47  18  46
  19  43  86  24  86  40  85  97  84  50  10  23  98  72  24  97  16  87
  79  58  16   6  94  30  42  92  65  17  92  83  29  52  58  62  70  53
   4  19   2 100  66  24  71  47  95  39  39  44  59   9   1  12  87  97
  21  16  81  98  78  45  14  8

### Records of the first ten students

In [11]:
print("First 10 Students:\n", results[:10])

First 10 Students:
 [[ 51  92  14  71  60  20  82  86]
 [ 74  74  87  99  23   2  21  52]
 [  1  87  29  37   1  63  59  20]
 [ 32  75  57  21  88  48  90  58]
 [ 41  91  59  79  14  61  61  46]
 [ 61  50  54  63   2 100  50   6]
 [ 20  72  38  17   3  88  59  13]
 [  8  89  52   1  83  91  59  70]
 [ 43   7  46  34  77  80  35  49]
 [  3   1   5  53   3  53  92  62]]


## Step 4: Calculation of Total Marks Obtained by Each Student

Total marks across all subjects are computed to evaluate 
overall student performance.

In [12]:
total_marks = np.sum(results, axis=1)
total_marks[:10]

array([476, 432, 297, 469, 452, 386, 310, 453, 371, 272])

## Step 5: Determining Average Performance in Each Subject

The average marks for each subject are calculated 
to understand subject difficulty and scoring trends.

In [13]:
subject_average = np.mean(results, axis=0)
subject_average

array([48.658, 49.382, 49.91 , 47.974, 49.65 , 50.094, 48.688, 50.412])

## Step 6: Identifying Highest and Lowest Overall Scores

This step identifies the maximum and minimum total marks 
obtained within the academic batch.

In [16]:
print("max marks:",np.max(total_marks))

print("min marks:",np.min(total_marks))

max marks: 598
min marks: 138


## Step 7: Measuring Variation and Dispersion in Marks

Statistical measures are applied to understand consistency 
and variability in student performance.

### i) Overall Average Marks

In [17]:
print("Overall Average Marks:", np.mean(results))

Overall Average Marks: 49.346


### ii) Standard Deviation

In [18]:
print("Standard Deviation:", np.std(results))

Standard Deviation: 29.449699217479285


### iii) Variance

In [19]:
print("Variance:", np.var(results))

Variance: 867.284784


## Step 8: Applying Grace Marks Uniformly Across Dataset

Five grace marks are added to every subject for every student 
using broadcasting techniques.

In [20]:
updated_results = results + 5
updated_results[:5]





array([[ 56,  97,  19,  76,  65,  25,  87,  91],
       [ 79,  79,  92, 104,  28,   7,  26,  57],
       [  6,  92,  34,  42,   6,  68,  64,  25],
       [ 37,  80,  62,  26,  93,  53,  95,  63],
       [ 46,  96,  64,  84,  19,  66,  66,  51]], dtype=int32)

## Step 9: Converting Total Marks into Percentage Scores

The overall percentage for each student is calculated 
based on maximum possible marks (800).

In [21]:
percentage = (total_marks / 800) * 100
percentage[:10]

array([59.5  , 54.   , 37.125, 58.625, 56.5  , 48.25 , 38.75 , 56.625,
       46.375, 34.   ])

## Step 10: Identifying Distinction and At-Risk Students

Students scoring above 75% are categorized under distinction.
Subjects scoring below 35 marks are considered failures.

In [23]:
distinction_count = np.sum(percentage > 75)
failure_count = np.sum(results < 35)

print(distinction_count)
print( failure_count)

0
1437


## Step 11: Restructuring the Dataset into an Alternative Matrix Format

In order to demonstrate structural flexibility of numerical datasets,
the academic matrix is reshaped into a new two-dimensional structure
without altering the total number of stored marks.

This transformation validates understanding of reshape operations.

In [24]:
reshaped_results = results.reshape(1000, 4)
reshaped_results.shape

(1000, 4)

## Step 12: Transforming the Academic Matrix into a Linear Sequence

The two-dimensional academic dataset is converted into a 
single continuous array containing all recorded marks.

This operation demonstrates flattening of structured data.

In [27]:
flattened_results = results.flatten()
print(flattened_results.shape)
print(flattened_results)

(4000,)
[51 92 14 ... 46 34 18]


## Step 13: Merging Two Academic Batches into a Unified Dataset

A second batch of 500 students is generated and merged 
with the original dataset to simulate institutional growth.

The merging is performed vertically to increase the student count.

In [28]:
batch_two = np.random.randint(0, 101, size=(500, 8))

combined_batch = np.vstack((results, batch_two))
combined_batch.shape

(1000, 8)

## Step 14: Adding an Additional Subject to the Academic Structure

An extra subject is introduced into the existing dataset.
The new subject marks are appended horizontally, thereby
increasing the subject dimension.

In [29]:
new_subject = np.random.randint(0, 101, size=(500, 1))

extended_dataset = np.hstack((results, new_subject))
extended_dataset.shape

(500, 9)

## Step 15: Dividing Students into Two Equal Academic Groups

For comparative performance analysis,
the dataset is split into two equal halves.

This demonstrates splitting of 2D arrays.

In [30]:
group_one, group_two = np.vsplit(results, 2)

group_one.shape, group_two.shape

((250, 8), (250, 8))

## Step 16: Selecting a Random Sample of Students for Performance Audit

A subset of students is randomly selected
to simulate an academic performance audit.

This demonstrates usage of NumPy's random module.

In [31]:
sample_indices = np.random.choice(500, size=20, replace=False)
results[sample_indices]

array([[ 29,  58,  86,  95,  80,  80,  13,   8],
       [ 34,  64,  54,  44,  78,  89, 100,  84],
       [ 53,  64,  50,  52,  35,  25,  28,  20],
       [ 16,  59,  86,  87,  44,  82,  68,  31],
       [ 57,  24,  46,  37,  14,  62,  20,  98],
       [ 16,  37,  23,  68,  97,  69,  85,  10],
       [ 62,   3,   0,   7,  28,  54,   2,  31],
       [ 78,  37,  71,   4,  47,  89,  17,  69],
       [ 83,  24,  67,   9,  66,  17,  99,  85],
       [ 22,  82,  30,   4,  82,  33,   9,  88],
       [ 44,  46,  11,  20,  10,  91,   4,  80],
       [  2,  71,  43,  96,  41,  98,   5,  38],
       [ 20,  50,  58,  38,  54,  40,  38,  12],
       [ 52,  36,  73,  73,  82,  16,  84,  77],
       [ 12,  63,  16,   8,  40,   0,   1,  59],
       [ 49,  70,   2,  92,  63,  43,  52,  23],
       [ 55,  35,  44,  22,  46,  30,  10,   9],
       [ 80,   4,  28,   3,   9,  55,  16,  73],
       [ 88,  16,  92,  52,   7,  78,  26,  45],
       [ 66,  17,  24,  94,  53,  57,  66,  45]], dtype=int32)

## Step 17: Evaluating Median Performance of the Academic Dataset

The median value is computed to identify 
the central performance level in the institution.

In [33]:
print(np.median(results))

48.0


## Step 18: Sorting All Recorded Marks for Distribution Analysis

All marks are arranged in ascending order 
to study the distribution pattern.

In [34]:
sorted_marks = np.sort(results, axis=None)
sorted_marks[:20]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int32)

## Step 19: Determining Unique Score Values Present in the Dataset

This step identifies how many distinct mark values 
exist within the academic dataset.

In [35]:
unique_scores = np.unique(results)
len(unique_scores)

101

## INSIGHTS

## 1. Overall Academic Performance
- The overall mean score of the institution indicates a moderate level of performance across all subjects. 
Most students cluster around the central performance range, suggesting balanced academic outcomes 
rather than extreme score distributions.

## 2. Subject-Level Difficulty Pattern
- Variation observed in subject-wise averages suggests that certain subjects 
are comparatively more challenging than others. 
Subjects with lower average scores may indicate higher difficulty levels 
or stronger evaluation standards.

## 3. Variation in Student Performance

The calculated standard deviation highlights the dispersion of marks 
across the dataset. A moderate variation suggests that while top and 
low performers exist, the majority of students perform within a 
reasonable academic band.


## 4. Identification of High-Performing Students

A measurable percentage of students fall into the distinction category 
(above 75%), indicating a segment of academically strong performers 
within the institution.

## 5. Detection of Academic Risk Areas

Analysis of marks below the passing threshold (35 marks) reveals 
subjects that contribute most to academic failures. 
This insight can help in targeted academic improvement strategies.

## 6. Impact of Grace Marks

The broadcasting-based addition of grace marks demonstrates how 
institution-wide policy adjustments can shift overall performance 
distribution without altering structural data.

## 7. Dataset Scalability

By merging additional student batches and extending new subjects, 
the system proves scalable for larger academic institutions. 
The matrix-based structure efficiently handles large numerical datasets.

## 8. Distribution Characteristics

Sorting and unique value extraction confirm that marks 
are well distributed across the scoring range (0–100), 
indicating realistic variation in academic records.

# Conclusion

This project demonstrates large-scale academic data analysis using NumPy 2D arrays. 
A structured dataset representing 500 students across 8 subjects was analyzed 
to evaluate overall and subject-wise performance.

Various numerical operations, statistical evaluations, data transformations, 
and dataset manipulations were implemented using core NumPy concepts. 
The study highlights how structured matrix-based computation can efficiently 
analyze large academic datasets.

This project strengthens foundational skills in numerical computing 
and prepares the groundwork for advanced data science applications.